version: '3.8'
services:
  backend:
    build: ./backend
    dockerfile: ./backend/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecovoz
      - NODE_ENV=production
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
  mongo:
  image: mongo
  container_name: ecovoz_mongo
  ports:
    - '27017:27017'
  volumes:
    - mongo_data:/data/db
volumes:
  mongo_data:

