services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ecovoz_frontend
    ports:
      - '3001:3000'
    depends_on:
      - backend
    networks:
      - ecovoz_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - VITE_API_BASE_URL=http://backend:4000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ecovoz_backend
    command: ["npm", "run", "start"]
    ports:
      - '4001:4000'
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - ecovoz_network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo
    container_name: ecovoz_mongo
    ports:
      - '27017:27017'
    env_file:
      - .env
    volumes:
      - ecovoz_mongo_data:/data/db
      - ./backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ecovoz_network
    healthcheck:
      test: ["CMD-SHELL", "mongo --eval 'db.adminCommand({ping: 1})' localhost:27017 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  ecovoz_mongo_data:

networks:
  ecovoz_network:
    driver: bridge
