version: '3.8'
services:
  backend:
    build: .
    dockerfile: ./backend/Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MONGO_URI=mongodb://mongo:27017/ecovoz
    depends_on:
      - mongo
  frontend:
    build: .
    dockerfile: ./frontend/Dockerfile
    ports:
      - '3000:3000'
  mongo:
    image: mongo
    ports:
      - '27017:27017'
