services:
  - type: web
    name: ecovoz-backend
    env: node
    plan: free
    region: oregon
    buildCommand: ./render-setup.sh
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
    healthCheckPath: /health
    disk:
      sizeGB: 0  # Mantido em 0 para evitar custo extra em planos gratuitos.
    timeoutSeconds: 60

  - type: web
    name: ecovoz-frontend
    env: static
    plan: free
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist  # Certifique-se que este é o caminho correto da pasta de build do frontend.
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://ecovoz-backend.onrender.com/api/$1
