services:
  - type: web
    name: ecovoz-backend
    env: node
    plan: free
    region: oregon
    buildCommand: |
      chmod +x render-setup.sh
      ./render-setup.sh
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_VERSION
        value: 20
    autoDeploy: true
    healthCheckPath: /health

  - type: web
    name: ecovoz-frontend
    env: static
    plan: free
    buildCommand: ./render-setup.sh
    staticPublishPath: dist
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /api/(.*)
        destination: https://ecovoz-backend.onrender.com/api/$1
