name: Commit Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Instalar dependências para o commitlint
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      # Passo 3: Rodar o commitlint nos últimos commits
      - name: Run Commitlint
        run: npx commitlint --from=HEAD~10 --to=HEAD
